// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detect.proto
#ifndef GRPC_detect_2eproto__INCLUDED
#define GRPC_detect_2eproto__INCLUDED

#include "detect.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace bugu_detect {
namespace service {
namespace v1 {

class BuguDetect final {
 public:
  static constexpr char const* service_full_name() {
    return "bugu_detect.service.v1.BuguDetect";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Detect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::bugu_detect::service::v1::DetectReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bugu_detect::service::v1::DetectReply>> AsyncDetect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bugu_detect::service::v1::DetectReply>>(AsyncDetectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bugu_detect::service::v1::DetectReply>> PrepareAsyncDetect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bugu_detect::service::v1::DetectReply>>(PrepareAsyncDetectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Detect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest* request, ::bugu_detect::service::v1::DetectReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Detect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest* request, ::bugu_detect::service::v1::DetectReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bugu_detect::service::v1::DetectReply>* AsyncDetectRaw(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bugu_detect::service::v1::DetectReply>* PrepareAsyncDetectRaw(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Detect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::bugu_detect::service::v1::DetectReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bugu_detect::service::v1::DetectReply>> AsyncDetect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bugu_detect::service::v1::DetectReply>>(AsyncDetectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bugu_detect::service::v1::DetectReply>> PrepareAsyncDetect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bugu_detect::service::v1::DetectReply>>(PrepareAsyncDetectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Detect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest* request, ::bugu_detect::service::v1::DetectReply* response, std::function<void(::grpc::Status)>) override;
      void Detect(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest* request, ::bugu_detect::service::v1::DetectReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bugu_detect::service::v1::DetectReply>* AsyncDetectRaw(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bugu_detect::service::v1::DetectReply>* PrepareAsyncDetectRaw(::grpc::ClientContext* context, const ::bugu_detect::service::v1::DetectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Detect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Detect(::grpc::ServerContext* context, const ::bugu_detect::service::v1::DetectRequest* request, ::bugu_detect::service::v1::DetectReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Detect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Detect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Detect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Detect(::grpc::ServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetect(::grpc::ServerContext* context, ::bugu_detect::service::v1::DetectRequest* request, ::grpc::ServerAsyncResponseWriter< ::bugu_detect::service::v1::DetectReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Detect<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Detect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Detect() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bugu_detect::service::v1::DetectRequest, ::bugu_detect::service::v1::DetectReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bugu_detect::service::v1::DetectRequest* request, ::bugu_detect::service::v1::DetectReply* response) { return this->Detect(context, request, response); }));}
    void SetMessageAllocatorFor_Detect(
        ::grpc::MessageAllocator< ::bugu_detect::service::v1::DetectRequest, ::bugu_detect::service::v1::DetectReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bugu_detect::service::v1::DetectRequest, ::bugu_detect::service::v1::DetectReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Detect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Detect(::grpc::ServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Detect(
      ::grpc::CallbackServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Detect<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Detect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Detect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Detect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Detect(::grpc::ServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Detect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Detect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Detect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Detect(::grpc::ServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Detect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Detect() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Detect(context, request, response); }));
    }
    ~WithRawCallbackMethod_Detect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Detect(::grpc::ServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Detect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Detect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Detect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bugu_detect::service::v1::DetectRequest, ::bugu_detect::service::v1::DetectReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bugu_detect::service::v1::DetectRequest, ::bugu_detect::service::v1::DetectReply>* streamer) {
                       return this->StreamedDetect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Detect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Detect(::grpc::ServerContext* /*context*/, const ::bugu_detect::service::v1::DetectRequest* /*request*/, ::bugu_detect::service::v1::DetectReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDetect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bugu_detect::service::v1::DetectRequest,::bugu_detect::service::v1::DetectReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Detect<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Detect<Service > StreamedService;
};

}  // namespace v1
}  // namespace service
}  // namespace bugu_detect


#endif  // GRPC_detect_2eproto__INCLUDED
