// Code generated by entc, DO NOT EDIT.

package artifact

import (
	"bugu/app/bugu/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileID), v))
	})
}

// ArtifactHash applies equality check predicate on the "artifact_hash" field. It's identical to ArtifactHashEQ.
func ArtifactHash(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArtifactHash), v))
	})
}

// ArtifactSize applies equality check predicate on the "artifact_size" field. It's identical to ArtifactSizeEQ.
func ArtifactSize(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArtifactSize), v))
	})
}

// ArtifactAddr applies equality check predicate on the "artifact_addr" field. It's identical to ArtifactAddrEQ.
func ArtifactAddr(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArtifactAddr), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileID), v))
	})
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFileID), v))
	})
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...uuid.UUID) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFileID), v...))
	})
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...uuid.UUID) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFileID), v...))
	})
}

// ArtifactHashEQ applies the EQ predicate on the "artifact_hash" field.
func ArtifactHashEQ(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArtifactHash), v))
	})
}

// ArtifactHashNEQ applies the NEQ predicate on the "artifact_hash" field.
func ArtifactHashNEQ(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldArtifactHash), v))
	})
}

// ArtifactHashIn applies the In predicate on the "artifact_hash" field.
func ArtifactHashIn(vs ...uuid.UUID) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldArtifactHash), v...))
	})
}

// ArtifactHashNotIn applies the NotIn predicate on the "artifact_hash" field.
func ArtifactHashNotIn(vs ...uuid.UUID) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldArtifactHash), v...))
	})
}

// ArtifactHashGT applies the GT predicate on the "artifact_hash" field.
func ArtifactHashGT(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldArtifactHash), v))
	})
}

// ArtifactHashGTE applies the GTE predicate on the "artifact_hash" field.
func ArtifactHashGTE(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldArtifactHash), v))
	})
}

// ArtifactHashLT applies the LT predicate on the "artifact_hash" field.
func ArtifactHashLT(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldArtifactHash), v))
	})
}

// ArtifactHashLTE applies the LTE predicate on the "artifact_hash" field.
func ArtifactHashLTE(v uuid.UUID) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldArtifactHash), v))
	})
}

// ArtifactSizeEQ applies the EQ predicate on the "artifact_size" field.
func ArtifactSizeEQ(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArtifactSize), v))
	})
}

// ArtifactSizeNEQ applies the NEQ predicate on the "artifact_size" field.
func ArtifactSizeNEQ(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldArtifactSize), v))
	})
}

// ArtifactSizeIn applies the In predicate on the "artifact_size" field.
func ArtifactSizeIn(vs ...int64) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldArtifactSize), v...))
	})
}

// ArtifactSizeNotIn applies the NotIn predicate on the "artifact_size" field.
func ArtifactSizeNotIn(vs ...int64) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldArtifactSize), v...))
	})
}

// ArtifactSizeGT applies the GT predicate on the "artifact_size" field.
func ArtifactSizeGT(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldArtifactSize), v))
	})
}

// ArtifactSizeGTE applies the GTE predicate on the "artifact_size" field.
func ArtifactSizeGTE(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldArtifactSize), v))
	})
}

// ArtifactSizeLT applies the LT predicate on the "artifact_size" field.
func ArtifactSizeLT(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldArtifactSize), v))
	})
}

// ArtifactSizeLTE applies the LTE predicate on the "artifact_size" field.
func ArtifactSizeLTE(v int64) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldArtifactSize), v))
	})
}

// ArtifactAddrEQ applies the EQ predicate on the "artifact_addr" field.
func ArtifactAddrEQ(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrNEQ applies the NEQ predicate on the "artifact_addr" field.
func ArtifactAddrNEQ(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrIn applies the In predicate on the "artifact_addr" field.
func ArtifactAddrIn(vs ...string) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldArtifactAddr), v...))
	})
}

// ArtifactAddrNotIn applies the NotIn predicate on the "artifact_addr" field.
func ArtifactAddrNotIn(vs ...string) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldArtifactAddr), v...))
	})
}

// ArtifactAddrGT applies the GT predicate on the "artifact_addr" field.
func ArtifactAddrGT(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrGTE applies the GTE predicate on the "artifact_addr" field.
func ArtifactAddrGTE(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrLT applies the LT predicate on the "artifact_addr" field.
func ArtifactAddrLT(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrLTE applies the LTE predicate on the "artifact_addr" field.
func ArtifactAddrLTE(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrContains applies the Contains predicate on the "artifact_addr" field.
func ArtifactAddrContains(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrHasPrefix applies the HasPrefix predicate on the "artifact_addr" field.
func ArtifactAddrHasPrefix(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrHasSuffix applies the HasSuffix predicate on the "artifact_addr" field.
func ArtifactAddrHasSuffix(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrEqualFold applies the EqualFold predicate on the "artifact_addr" field.
func ArtifactAddrEqualFold(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldArtifactAddr), v))
	})
}

// ArtifactAddrContainsFold applies the ContainsFold predicate on the "artifact_addr" field.
func ArtifactAddrContainsFold(v string) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldArtifactAddr), v))
	})
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v Method) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMethod), v))
	})
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v Method) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMethod), v))
	})
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...Method) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMethod), v...))
	})
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...Method) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMethod), v...))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Artifact {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Artifact(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// HasAffiliatedFile applies the HasEdge predicate on the "affiliated_file" edge.
func HasAffiliatedFile() predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AffiliatedFileTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AffiliatedFileTable, AffiliatedFileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAffiliatedFileWith applies the HasEdge predicate on the "affiliated_file" edge with a given conditions (other predicates).
func HasAffiliatedFileWith(preds ...predicate.File) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AffiliatedFileInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AffiliatedFileTable, AffiliatedFileColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAffiliatedUser applies the HasEdge predicate on the "affiliated_user" edge.
func HasAffiliatedUser() predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AffiliatedUserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AffiliatedUserTable, AffiliatedUserPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAffiliatedUserWith applies the HasEdge predicate on the "affiliated_user" edge with a given conditions (other predicates).
func HasAffiliatedUserWith(preds ...predicate.User) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AffiliatedUserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AffiliatedUserTable, AffiliatedUserPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Artifact) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Artifact) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Artifact) predicate.Artifact {
	return predicate.Artifact(func(s *sql.Selector) {
		p(s.Not())
	})
}
