// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
